import sqlite3

con=sqlite3.connect("scoreboard.db")
con.execute('CREATE TABLE leaders (team TEXT,score INTEGER)')
cur=con.cursor()
cur.execute("INSERT INTO leaders (team,score) VALUES (?,?)",("perfect blue",15000) )
cur.execute("INSERT INTO leaders (team,score) VALUES (?,?)",("Gryffindor",14900) )
cur.execute("INSERT INTO leaders (team,score) VALUES (?,?)",("InfoSecIITR",11980) )
cur.execute("INSERT INTO leaders (team,score) VALUES (?,?)",("ALLES!",14100) )
cur.execute("INSERT INTO leaders (team,score) VALUES (?,?)",("Doxepticons",13500) )
cur.execute("INSERT INTO leaders (team,score) VALUES (?,?)",("SDSLabs",13000) )
cur.execute("INSERT INTO leaders (team,score) VALUES (?,?)",("MOODY ji",12900) )
cur.execute("INSERT INTO leaders (team,score) VALUES (?,?)",("ByteBandits",12800) )
cur.execute("INSERT INTO leaders (team,score) VALUES (?,?)",("NULLCON",12700) )
cur.execute("INSERT INTO leaders (team,score) VALUES (?,?)",("IITR_hackerzz",12000) )
cur.execute("INSERT INTO leaders (team,score) VALUES (?,?)",("Starks",11900) )
cur.execute("INSERT INTO leaders (team,score) VALUES (?,?)",("Noobies",10000) )
print("created !!")
con.commit()
con.close()